"""
Django settings for informes project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from configurations import Configuration, values

class Common(Configuration):

    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    ENVIRONMENT = values.Value(environ_prefix=None, default='DEVELOPMENT')

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = values.SecretValue()

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = values.BooleanValue(False)

    TEMPLATE_DEBUG = values.BooleanValue(DEBUG)

    ALLOWED_HOSTS = []


    # Application definition

    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',

        # Third party
        'django_extensions',

        'informes.informesmen',
        'informes.departamentos',
        'informes.questions',
        'informes.persons',
        'informes.users'
    )

    MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    )

    ROOT_URLCONF = 'informes.urls'

    TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)


    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)


    WSGI_APPLICATION = 'informes.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/1.8/ref/settings/#databases

    DATABASES = values.DatabaseURLValue(
        'sqlite:///{}'.format(os.path.join(BASE_DIR, 'db.sqlite3'))
    )


    # Internationalization
    # https://docs.djangoproject.com/en/1.8/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    DATE_INPUT_FORMATS = ('%m/%d/%Y', '%Y-%m-%d',)


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.8/howto/static-files/

    STATIC_URL = '/static/'
    STATIC_ROOT = 'staticfiles'

    MEDIA_ROOT = 'media'
    MEDIA_URL = '/media/'

    AUTH_USER_MODEL = 'users.User'
    LOGIN_REDIRECT_URL = '/'

    CORS_ORIGIN_ALLOW_ALL = True

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': '127.0.0.1:11211',
        }
    }

    PROTOCOL = "http"

    DOMAIN = values.Value(environ_prefix=None)

    SITE_NAME = values.Value(environ_prefix=None)

    ACTIVATION_URL = values.Value(environ_prefix=None)

    PASSWORD_RESET_CONFIRM_URL = values.Value(environ_prefix=None)

    DEFAULT_FROM_EMAIL = values.Value()
    EMAIL_HOST = values.Value()
    EMAIL_HOST_USER = values.Value()
    EMAIL_HOST_PASSWORD = values.Value()
    EMAIL_PORT = values.IntegerValue()
    EMAIL_USE_TLS = values.BooleanValue(False)

class Development(Common):
    """
    The in-development settings and the default configuration.
    """

    DEBUG = True

    TEMPLATE_DEBUG = True

    ALLOWED_HOSTS = []

class Staging(Common):
    """
    The in-staging settings.
    """

    PROTOCOL = 'https'

class Production(Staging):
    """
    The in-production settings.
    """
    STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'